name: Darknet Continuous Integration

on: [push]

jobs:
  cygwin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Install Cygwin'
      run: |
        choco install cygwin -y
        choco install cyg-get -y
        cyg-get tar findutils

    - name: 'Build'
      env:
        GHWS: ${{ github.workspace }}
      run: |
        path C:\tools\cygwin\bin
        bash -c 'find "/cygdrive/c/Program Files (x86)/" -type d'
      shell: cmd

    - uses: actions/upload-artifact@v2
      with:
        name: msvc
        path: ${{ github.workspace }}/msvc.tar
