name: Darknet Continuous Integration

on: [push]

jobs:
  cygwin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Install Cygwin'
      run: |
        choco install cygwin -y
        choco install cyg-get -y
        cyg-get tar

    - name: 'Build'
      run: |
        path C:\tools\cygwin\bin
        bash -c 'ln -s "/cygdrive/c/Program Files (x86)/Microsoft Visual Studio" msvc'
        bash -c 'tar cvf msvc.tar msvc/'
      shell: cmd

    - uses: actions/upload-artifact@v2
      with:
        name: msvc
        path: ${{ github.workspace }}/msvc.tar
